name: Run Known-Good Proofs

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-proofs:
    runs-on: ubuntu-latest
    name: Check Proofs
    steps:
      - uses: actions/checkout@v2
      - name: Install CVC5
        run: sudo apt install cvc5

      - name: Install Enough TexLive
        run: sudo apt install --no-install-recommends texlive-base texlive-science texlive-latex-extra

      - name: Build Domino
        run: |
          cargo build --release -p domino
          echo "DOMINO=$(pwd)/target/release/domino">>$GITHUB_ENV

      - name: Run proofs
        run: "./scripts/test-known-examples.sh || exit 1"

      - uses: actions/upload-artifact@v4
        with:
          name: Project PDFs
          path: ./example-projects/**/_build/latex/Theorem_*.pdf
          retention-days: 14

